# TODO: other values, who knows!
prefix: 'tt!'
skins:
    - name: 'default'
      # Ordered as: [Background, I, L, J, S, Z, T, O, Garbage, Ghost]
      # This can be any text. If you're using custom emotes, use the <:name:id> format.
      # Due to discord's limits with embeds, their names should have at most two characters
      # or the text size exceeds 4096 chars
      pieces: ['â¬›', 'ğŸŸ¦', 'ğŸŸ§', 'ğŸŸ¦', 'ğŸŸ©', 'ğŸŸ¥', 'ğŸŸª', 'ğŸŸ¨', 'ğŸ”³', 'â—½']

      # The emotes for the buttons
      controls:
          # Left/right
          drag: ['â—€ï¸', 'â–¶ï¸']
          # DAS left/right
          das: ['âª', 'â©']
          # Soft drop/hard drop
          drop: ['ğŸ”½', 'â¬']
          # Rotate ccw, cw, 2x
          rotate: ['â†ªï¸', 'â†©ï¸', 'ğŸ”„']
          swap: 'ğŸ”€'

status-channel: null

redis: 'auto' # 'fakeredis', 'aioredis' or 'auto'; use aioredis if you are using a server
