# TODO: other values, who knows!
prefix: 'tt!'
skins:
    - name: 'default'
      # Ordered as: [Background, I, L, J, S, Z, T, O, Garbage, Ghost]
      # This can be any text. If you're using custom emotes, use the <:name:id> format.
      # Due to discord's limits with embeds, their names should have at most two characters
      # or the text size exceeds 4096 chars
      pieces: ['â¬›', 'ğŸŸ¦', 'ğŸŸ§', 'ğŸŸ¦', 'ğŸŸ©', 'ğŸŸ¥', 'ğŸŸª', 'ğŸŸ¨', 'ğŸ”³', 'â—½']

      # The emotes for the buttons
      controls:
          left: 'â—€ï¸'
          right: 'â–¶ï¸'
          das-left: 'âª'
          das-right: 'â©'
          soft-drop: 'ğŸ”½'
          hard-drop: 'â¬'
          rotate-ccw: 'â†ªï¸'
          rotate-cw: 'â†©ï¸'
          rotate-2cw: 'ğŸ”„'
          swap: 'ğŸ”€'

test-servers: []
status-channel: null

redis: 'auto' # 'fakeredis', 'aioredis' or 'auto'; use aioredis if you are using a server
